# $FreeBSD$

freebsd_instance:
  image: freebsd-13-1-release-amd64

env:
  CIRRUS_CLONE_DEPTH: 1
  CIRRUS_CLONE_SUBMODULES: true

task:
  install_script:
  - pkg install -y
    avahi-libdns cmake curl ninja qt5-core
  script:
  - mkdir build
  - cd build
  - cmake -DBARRIER_BUILD_TESTS=OFF -GNinja ..
  - ninja
